[build]
  publish = "public/"
  command = "gatsby build --prefix-paths && mkdir -p docs/community && mv public/* docs/community && mv docs public/ && mv public/docs/community/_redirects public"
[build.environment]
  NPM_VERSION = "6"
